/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.gestionturnoshospital;

/**
 *
 * @author samuelastudillo
 */
public class DlgEliminarEnfermera extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgEliminarEnfermera.class.getName());

    /**
     * Creates new form DlgEliminarEnfermera
     */
    private final EnfermeraService enfSvc;

    public DlgEliminarEnfermera(java.awt.Dialog owner, boolean modal, EnfermeraService enfSvc) {
        super(owner, modal);
        this.enfSvc = enfSvc;
        initComponents();
        configurarRangosYPrecargar();
        pack();
        setLocationRelativeTo(owner);
    }
    private void configurarRangosYPrecargar() {
    int total = enfSvc.count();

    spIndice.setModel(new javax.swing.SpinnerNumberModel(
        total > 0 ? 1 : 0,
        total > 0 ? 1 : 0,
        total,
        1
    ));

    // Cambiar resumen al mover el índice
    spIndice.addChangeListener(e -> {
        int idx = ((Number) spIndice.getValue()).intValue() - 1;
        cargarResumen(idx);
    });

    if (total > 0) {
        cargarResumen(0);
        btnEliminar.setEnabled(true);
    } else {
        lblResumen.setText("No hay enfermeras.");
        btnEliminar.setEnabled(false);
    }
}

    private void cargarResumen(int idx) {
        if (!enfSvc.indiceValido(idx)) {
            lblResumen.setText("Índice inválido.");
            btnEliminar.setEnabled(false);
            return;
        }
        var e = enfSvc.listar().get(idx); // o getPorIndice(idx)
        String skills = String.join(", ", e.getSkills());
        lblResumen.setText(
            String.format("<html><b>%s</b> (RUT: %s)<br/>Horas máx.: %d | Skills: %s</html>",
                e.getNombre(), e.getRut(), e.getHorasMensualMax(), skills)
        );
        btnEliminar.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JLabel = new javax.swing.JLabel();
        spIndice = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        lblResumen = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Eliminar Enfermera");

        JLabel.setText("Indice:");

        spIndice.setPreferredSize(new java.awt.Dimension(80, 23));

        jLabel3.setText("Seleccionada:");

        lblResumen.setForeground(new java.awt.Color(102, 102, 102));
        lblResumen.setToolTipText("");
        lblResumen.setPreferredSize(new java.awt.Dimension(200, 60));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLabel)
                        .addGap(18, 18, 18)
                        .addComponent(spIndice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel)
                    .addComponent(spIndice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResumen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (enfSvc.count() == 0) return;

        int idx = ((Number) spIndice.getValue()).intValue() - 1;
        if (!enfSvc.indiceValido(idx)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Índice inválido.");
            return;
        }
        var e = enfSvc.listar().get(idx);

        int r = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Eliminar a " + e.getNombre() + " (RUT: " + e.getRut() + ")?",
            "Confirmar eliminación",
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (r != javax.swing.JOptionPane.YES_OPTION) return;

        try {
            var eliminada = enfSvc.eliminar(idx); // ✅ usa tu método existente
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Enfermera eliminada: " + eliminada.getNombre() + " (RUT: " + eliminada.getRut() + ")"
            );
            dispose();
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
    try {
        for (var info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ignored) {}

    java.awt.EventQueue.invokeLater(() -> {
        EnfermeraService enfSvc = new EnfermeraService(); // o tu getter compartido
        DlgEliminarEnfermera dialog = new DlgEliminarEnfermera(
            (java.awt.Dialog) null, true, enfSvc
        );
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override public void windowClosing(java.awt.event.WindowEvent e) { System.exit(0); }
        });
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblResumen;
    private javax.swing.JSpinner spIndice;
    // End of variables declaration//GEN-END:variables
}
