/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.gestionturnoshospital;
import java.util.logging.Logger;

/**
 *
 * @author samuelastudillo
 */
public class DlgListarEnfermeras extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgListarEnfermeras.class.getName());
    private final EnfermeraService enfSvc;
    

    /**
     * Creates new form DlgListarEnfermeras
     */
    public DlgListarEnfermeras(java.awt.Dialog parent, boolean modal, EnfermeraService enfSvc) {
        super(parent, modal);
        this.enfSvc = enfSvc;
        initComponents();
        pack();
        setLocationRelativeTo(parent);
        configurarTabla();
        cargarTabla();

        // aquí podrías llamar cargarTabla();
    }
    private void configurarTabla() {
    String[] cols = {"#", "Nombre", "RUT", "Horas Máx.", "Horas Acum.", "Skills"};

    javax.swing.table.DefaultTableModel model =
        new javax.swing.table.DefaultTableModel(cols, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };

    tblEnfermeras.setModel(model);
    tblEnfermeras.setAutoCreateRowSorter(true);   // ordenar por columnas
}
    void cargarTabla() {
    var model = (javax.swing.table.DefaultTableModel) tblEnfermeras.getModel();
    model.setRowCount(0); // limpia filas

    java.util.List<Enfermera> lista = enfSvc.listar();
    for (int i = 0; i < lista.size(); i++) {
        Enfermera e = lista.get(i);
        String skills = String.join(", ", e.getSkills());
        Object[] fila = {
            i + 1,
            e.getNombre(),
            e.getRut(),
            e.getHorasMensualMax(), // ajusta al nombre real del getter
            e.getHorasAcumuladas(),       // o 0 si aún no lo manejas
            skills
        };
        model.addRow(fila);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spEnfermeras = new javax.swing.JScrollPane();
        tblEnfermeras = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblEnfermeras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spEnfermeras.setViewportView(tblEnfermeras);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spEnfermeras, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spEnfermeras, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
    // Look & Feel (opcional)
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        Logger.getLogger(DlgListarEnfermeras.class.getName())
              .log(java.util.logging.Level.SEVERE, null, ex);
    }

    // Crear y mostrar el diálogo
    java.awt.EventQueue.invokeLater(() -> {
        // instancia del servicio para esta prueba (o usa tu getter estático si tienes uno)
        EnfermeraService enfSvc = new EnfermeraService();
        // EnfermeraService enfSvc = GestionTurnosHospital.getEnfSvc();

        // Ojo: tu constructor ahora pide Dialog + boolean + servicio
        DlgListarEnfermeras dialog = new DlgListarEnfermeras(
            (java.awt.Dialog) null,   // parent
            true,                     // modal
            enfSvc                    // servicio
        );

        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane spEnfermeras;
    private javax.swing.JTable tblEnfermeras;
    // End of variables declaration//GEN-END:variables
}
