/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestionturnoshospital;

/**
 *
 * @author samuelastudillo
 */

public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnImportar = new javax.swing.JButton();
        btnGestionar = new javax.swing.JButton();
        btnAsignar = new javax.swing.JButton();
        btnCalendario = new javax.swing.JButton();
        btnConflictos = new javax.swing.JButton();
        filtrarDisponibles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Gestion de Turnos de Hospital");

        btnSalir.setBackground(new java.awt.Color(255, 102, 102));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnImportar.setText("Importar datos");
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });

        btnGestionar.setText("Gestionar Datos");
        btnGestionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarActionPerformed(evt);
            }
        });

        btnAsignar.setText("Asignar Turnos");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        btnCalendario.setText("Visualizar Calendario");
        btnCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarioActionPerformed(evt);
            }
        });

        btnConflictos.setText("Conflictos");
        btnConflictos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConflictosActionPerformed(evt);
            }
        });

        filtrarDisponibles.setText("Enfermeras Disponibles");
        filtrarDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarDisponiblesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(104, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnConflictos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalendario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAsignar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImportar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGestionar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(filtrarDisponibles)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(btnImportar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGestionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAsignar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalendario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConflictos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filtrarDisponibles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarActionPerformed
        
        try {
            javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
            fc.setDialogTitle("Selecciona la carpeta que contiene enfermeras/areas/disponibilidades");
            fc.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
            int r = fc.showOpenDialog(this);
            if (r != javax.swing.JFileChooser.APPROVE_OPTION) return;

            java.io.File dir = fc.getSelectedFile();
            java.nio.file.Path folder = dir.toPath();

            java.util.List<java.nio.file.Path> csvs = new java.util.ArrayList<>();
            try (java.util.stream.Stream<java.nio.file.Path> st = java.nio.file.Files.list(folder)) {
                st.filter(p -> p.getFileName().toString().toLowerCase().endsWith(".csv"))
                  .forEach(csvs::add);
            }
            if (csvs.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontraron .csv en la carpeta.",
                        "Importar datos", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            java.nio.file.Path enfCsv = null, areaCsv = null, dispCsv = null;

            for (java.nio.file.Path p : csvs) {
                String header;
                try (java.io.BufferedReader br = java.nio.file.Files.newBufferedReader(p, java.nio.charset.StandardCharsets.UTF_8)) {
                    header = br.readLine();
                }
                if (header == null) continue;

                String h = sanitizeHeader(header).toLowerCase();
                // OJO: todo en minúsculas al comparar:
                if (h.equals("rut,nombre,horasmensualmax,skills") && enfCsv == null) {
                    enfCsv = p;
                } else if (h.equals("id,nombre,cuposmanana,cupostarde,cuposnoche,skillsrequeridas") && areaCsv == null) {
                    areaCsv = p;
                } else if ((h.equals("rut,fecha,bloque,disponible") || h.equals("rut,fecha,bloque,area,disponible")) && dispCsv == null) {
                    dispCsv = p;
                }
            }

            if (enfCsv == null || areaCsv == null || dispCsv == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Faltan CSV requeridos:\n" +
                    (enfCsv == null ? " - enfermeras (rut,nombre,horasMensualMax,skills)\n" : "") +
                    (areaCsv == null ? " - areas (id,nombre,cuposManana,cuposTarde,cuposNoche,skillsRequeridas)\n" : "") +
                    (dispCsv == null ? " - disponibilidades (rut,fecha,bloque[,area],disponible)\n" : ""),
                    "Importar datos", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            EnfermeraService enfSvc = GestionTurnosHospital.getEnfSvc();
            Hospital hospital = GestionTurnosHospital.getHospital();

            DlgImportarDatos.importEnfermeras(enfCsv, enfSvc);
            DlgImportarDatos.importAreas(areaCsv, hospital);
            DlgImportarDatos.importDisponibilidades(dispCsv, enfSvc);
            GestionTurnosHospital.setUltimoCsvDisponibilidades(dispCsv);
            


            javax.swing.JOptionPane.showMessageDialog(this,
                "Importación completada:\n" +
                "Enfermeras: " + enfSvc.count() + "\n" +
                "Áreas: " + hospital.getAreas().size() + "\n" +
                "Disponibilidades: OK",
                "Importar datos", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error importando CSV", ex);
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error al importar: " + ex.getMessage(),
                "Importar datos", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnImportarActionPerformed

    private static String sanitizeHeader(String header) {
        if (header == null) return null;
        return header.replace("\uFEFF", "").trim();
    }
    private void abrirDlgFiltrarDisponibles(){
        new DlgFiltrarDisponibles(this, true, GestionTurnosHospital.getEnfSvc())
                .setVisible(true);      
    }
    
    private void btnConflictosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConflictosActionPerformed
        DlgConflictos dlg = new DlgConflictos(this, GestionTurnosHospital.getHospital(),GestionTurnosHospital.getEnfSvc());
        dlg.setVisible(true);
    }//GEN-LAST:event_btnConflictosActionPerformed

    private void btnCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalendarioActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        new DlgAsignarTurnos(this,true,GestionTurnosHospital.getEnfSvc(),GestionTurnosHospital.getHospital())
        .setVisible(true);
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnGestionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarActionPerformed
        DlgGestionDatos dlg = new DlgGestionDatos(this, true,GestionTurnosHospital.getEnfSvc());
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);
    }//GEN-LAST:event_btnGestionarActionPerformed

    private void filtrarDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarDisponiblesActionPerformed
    abrirDlgFiltrarDisponibles();    }//GEN-LAST:event_filtrarDisponiblesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnCalendario;
    private javax.swing.JButton btnConflictos;
    private javax.swing.JButton btnGestionar;
    private javax.swing.JButton btnImportar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton filtrarDisponibles;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
